# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIjbe23Ee8hLTrr4IS0KgtvLiDNMSlEL
"""

import pandas as pd
import numpy as np
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df=pd.read_excel("/content/drive/MyDrive/B_Cancer.xlsx")
df.head()

df=df.drop(columns=['id'])
df['diagnosis']=df['diagnosis'].map({'M':1,'B':0})

x=df.drop(columns=['diagnosis'])
y=df['diagnosis']

scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
x_scaled

x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=42)
print(x_train.shape)

from keras.models import Sequential
from keras.layers import Dense,Input

model=Sequential()
model.add(Input(shape=(x_train.shape[1],)))
model.add(Dense(16,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x_train,y_train,epochs=100,verbose=2)
loss,accuracy=model.evaluate(x_test,y_test)
print(f'Test Loss:{loss:.4f},Test Accuracy :{accuracy:.4f}')

user_input = np.array([[17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871,
                        25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189,
                        28.0, 24.0, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189]])

user_input_scaled = scaler.transform(user_input)

prediction = model.predict(user_input_scaled)

print("Malignant (Cancer Detected)" if prediction[0][0] >= 0.5 else "Benign (No Cancer)")

prediction = model.predict(x_test)
print(prediction)

import joblib
model.save("breast_cancer_ann.keras")
joblib.dump(scaler,'scaler.pkl')